os:
  - linux
language: java
sudo: false # faster builds
cache:
  directories:
    - $HOME/.gradle
before_install:
  - java -version

#addons:
#  apt:
#    packages:
#      - oracle-java8-installer
#jdk:
#
jdk:
  - openjdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)